"""
    write_geometry_file(input, output)

Write a .geom file for crystFEL using information from the supplied hdf5 master file.
input is a hdf5 data master file.
output is the string path of the .geom file.
"""
function write_geometry_file(input, output)
    #Geom file#
    geomfile = open(output,"w")

    write(geomfile, ";Geometry file generated by XDIPFSP\n")
    write(geomfile, ";Detector type: " * input["entry/instrument/detector/description"][] * "\n\n")

    write(geomfile, ";Detector characteristics:\n")
    write(geomfile, "clen = " * string(input["entry/instrument/detector/detector_distance"][]) * "\n")
    pixel_size = input["entry/instrument/detector/x_pixel_size"][]
    write(geomfile, "res = " * string(1/pixel_size) * " ;"*string(pixel_size*1000000)*"um pixel size\n\n")

    write(geomfile, ";Beam characteristics:\n")
    wavelength = input["entry/instrument/beam/incident_wavelength"][]
    write(geomfile, ";wavelength: " * string(wavelength) * " Angstroms \n")
    # E = hc/l 
    # hc = 12398.419 eV.A
    photon_energy = 12398.419/wavelength
    write(geomfile, "photon_energy = " * string(photon_energy) * "\n")
    write(geomfile, "adu_per_photon = 1\n")
    write(geomfile, ";adu_per_eV " * string(1/photon_energy) * "\n\n")

    write(geomfile, ";Data and mask paths\n")
    write(geomfile, "mask = /data/mask\n")
    write(geomfile, "mask_good = 0x0\n")
    write(geomfile, "mask_bad = 0x1\n")
    write(geomfile, "data = /data/data\n\n")

    write(geomfile, ";panel descriptons\n")
    write(geomfile, "panel0/min_fs = 0
panel0/min_ss = 0
panel0/max_fs = 3109
panel0/max_ss = 3268\n")
    write(geomfile, "panel0/corner_x = -" * string(input["entry/instrument/detector/beam_center_x"][]) * "\n")
    write(geomfile, "panel0/corner_y = -" * string(input["entry/instrument/detector/beam_center_y"][]) * "\n")
    write(geomfile, "panel0/fs = x
panel0/ss = y")
    close(geomfile)
end